name: Cargo Test

on:
  push:
    paths-ignore:
    - README.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get Keybase
      run: curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
    - name: Disable Keybase Repo
      run: sudo touch /etc/default/keybase
    - name: Install Keybase
      run: sudo apt install ./keybase_amd64.deb
    - name: Keybase Login
      env:
        KEYBASE_USERNAME: ${{ secrets.KEYBASE_USERNAME }}
        KEYBASE_PAPERKEY: ${{ secrets.KEYBASE_PAPERKEY }}
      run: keybase oneshot
    - name: Run tests
      run: cargo test --verbose
    - name: Keybase Logout
      if: always()
      run: keybase logout
